version: "3.8"

services:
  sftp-server:
    build: .
    container_name: sftp-server
    ports:
      - "2222:2222" # Expose SFTP port
    volumes:
      - ./sftp_data:/app/sftp_data 
      - ./host_key:/app/host_key
    restart: unless-stopped
